apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasti.fullname" . }}-operator-controller-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "elasti-operator.controlPlaneLabels" . | nindent 4 }}
    {{- include "elasti-operator.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-operator.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.elastiController.service.type }}
  selector:
    {{- include "elasti-operator.controlPlaneLabels" . | nindent 4 }}
    {{- include "elasti.selectorLabels" (dict "context" . "name" "elasti") | nindent 4 }}
  ports:
  - port: {{ .Values.elastiController.service.port }}
    targetPort: {{ .Values.elastiController.service.port }}
    protocol: TCP
    name: custom-port