{{- if .Values.global.enableMonitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "elasti.fullname" . }}-operator-controller-manager-metrics-monitor
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "elasti-operator.serviceMonitorLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-operator.serviceMonitorAnnotations" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: custom-port
    scheme: http
  selector:
    matchLabels:
      {{- include "elasti-operator.controlPlaneLabels" . | nindent 6 }}
{{- end}}