apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasti.fullname" . }}-resolver-service
  namespace: '{{ .Release.Namespace }}'
  labels:
    app.kubernetes.io/prometheus: elasti-resolver # used serviceMonitor to define the jobLabel
    {{- include "elasti-resolver.serviceLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-resolver.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.elastiResolver.service.type }}
  selector:
    {{- include "elasti-resolver.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.elastiResolver.service.port }}
    targetPort: {{ .Values.elastiResolver.service.port }}
    protocol: TCP
    name: http-resolver
  - port: {{ .Values.elastiResolver.reverseProxyService.port }}
    targetPort: {{ .Values.elastiResolver.reverseProxyService.port }}
    protocol: TCP
    name: http-resolver-reverse-proxy