{{- if .Values.global.enableMonitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "elasti.fullname" . }}-resolver-metrics-monitor
  namespace: '{{ .Release.Namespace }}'
  labels:
    group: elasti
    {{- include "elasti-resolver.serviceMonitorLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-resolver.serviceMonitorAnnotations" . | nindent 4 }}
spec:
  endpoints:
  - path: /metrics
    port: http-resolver
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: elasti-resolver
{{- end}}