apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasti.fullname" . }}-operator-controller-manager
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "elasti-operator.serviceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-operator.serviceAccountAnnotations" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasti.fullname" . }}-resolver
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "elasti-resolver.serviceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "elasti-resolver.serviceAccountAnnotations" . | nindent 4 }}
