apiVersion: elasti.truefoundry.com/v1alpha1
kind: ElastiService
metadata:
  name: redis-statefulset
  namespace: target
spec:
  service: redis-statefulset
  minTargetReplicas: 1
  cooldownPeriod: 100
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: redis-statefulset
  triggers:
    - metadata:
        query: round(sum(rate(envoy_http_downstream_rq_total{container="istio-proxy",destination_service_name="redis-statefulset"}[1m])),0.001) or vector(0)
        serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
        threshold: "0.01"
      type: prometheus
