name: E2E Tests with Kuttl

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  kuttl-tests:
    name: Run Kuttl E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install specific Helm version
        uses: azure/setup-helm@v3
        with:
          version: 'v3.12.3'

      - name: Build and push images
        working-directory: ./tests/e2e
        run: |
          make build-images
      
      - name: Install Kind with Registry
        uses: helm/kind-action@v1.5.0
        with:
          install_only: true

      - name: Create Kind cluster
        working-directory: ./tests/e2e
        run: |
          make kind-up
      
      - name: Install dependencies
        working-directory: ./tests/e2e
        run: |
          make apply-deps

      - name: Install Kuttl
        run: |
          curl -Lo kuttl.tar.gz https://github.com/kudobuilder/kuttl/releases/download/v0.22.0/kuttl_0.22.0_linux_x86_64.tar.gz
          tar -xvf kuttl.tar.gz
          sudo mv kubectl-kuttl /usr/local/bin/
          kubectl kuttl version

      - name: Run Kuttl E2E Tests
        working-directory: ./tests/e2e
        run: |
          kubectl kuttl test --config ./kuttl-test.yaml
